// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEgi93jlshhfDuIWlxdwjqdnKnn-im5sY',
    appId: '1:487158011158:web:caf970d1b2b7d45e50ac37',
    messagingSenderId: '487158011158',
    projectId: 'firestone-ea8f5',
    authDomain: 'firestone-ea8f5.firebaseapp.com',
    storageBucket: 'firestone-ea8f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc7g5hLM-4T4NAOserFQ4y2vDQahvUW8A',
    appId: '1:487158011158:android:104b800ae7dceb2650ac37',
    messagingSenderId: '487158011158',
    projectId: 'firestone-ea8f5',
    storageBucket: 'firestone-ea8f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAoIJPkcyf9V1vEgRsU9ACPU67ZbisexI',
    appId: '1:487158011158:ios:c6977ad39283453b50ac37',
    messagingSenderId: '487158011158',
    projectId: 'firestone-ea8f5',
    storageBucket: 'firestone-ea8f5.appspot.com',
    iosBundleId: 'com.example.firestone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAoIJPkcyf9V1vEgRsU9ACPU67ZbisexI',
    appId: '1:487158011158:ios:c6977ad39283453b50ac37',
    messagingSenderId: '487158011158',
    projectId: 'firestone-ea8f5',
    storageBucket: 'firestone-ea8f5.appspot.com',
    iosBundleId: 'com.example.firestone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEgi93jlshhfDuIWlxdwjqdnKnn-im5sY',
    appId: '1:487158011158:web:5f69ba618dab8b9a50ac37',
    messagingSenderId: '487158011158',
    projectId: 'firestone-ea8f5',
    authDomain: 'firestone-ea8f5.firebaseapp.com',
    storageBucket: 'firestone-ea8f5.appspot.com',
  );

}